FROM node:24-alpine

WORKDIR /app

# Copy built dist and package files
COPY dist ./dist
COPY package*.json ./

# Install only production dependencies
RUN npm ci --only=production

# Expose port
EXPOSE 3000

# Start
CMD ["node", "dist/index.js"]
